from enum import StrEnum


class ReasonCode(StrEnum):
    NORMALIZED = "NORMALIZED"
    METADATA_VALID = "METADATA_VALID"
    METADATA_INVALID = "METADATA_INVALID"
    EXACT_DUPLICATE = "EXACT_DUPLICATE"
    LEXICAL_DUPLICATE = "LEXICAL_DUPLICATE"
    SEMANTIC_DUPLICATE = "SEMANTIC_DUPLICATE"
    EVENT_CLUSTERED = "EVENT_CLUSTERED"
    CLAIM_UNSUPPORTED = "CLAIM_UNSUPPORTED"
    CLAIM_MISSING_EVIDENCE = "CLAIM_MISSING_EVIDENCE"
    PRODUCT_IMPLICATION_MISSING = "PRODUCT_IMPLICATION_MISSING"
    SCORE_MINIMUM_FAILED = "SCORE_MINIMUM_FAILED"
    TOTAL_SCORE_FAILED = "TOTAL_SCORE_FAILED"
    LOW_CONFIDENCE = "LOW_CONFIDENCE"
    CONFIDENCE_ACCEPTED = "CONFIDENCE_ACCEPTED"
    CATEGORY_CAP = "CATEGORY_CAP"
    TOTAL_CAP = "TOTAL_CAP"
    LANGUAGE_QA_FAILED = "LANGUAGE_QA_FAILED"
    ACCEPTED = "ACCEPTED"
    STAGE_ERROR = "STAGE_ERROR"
